In [2]:
# Importar la biblioteca os para verificar la ruta de trabajo
import os
# Mostrar la ruta actual del notebook (útil para confirmar ubicación de archivos)
os.getcwd()

'C:\\Users\\PGF\\Documents\\PGF_JUPYTER_Placilla'

In [3]:
# Importar la biblioteca pandas para análisis de datos
import pandas as pd
# Cargar el archivo CSV del datacenter en un DataFrame
df_dc = pd.read_csv("synthetic_datacenter_hourly_3days.csv")
# Cargar el archivo CSV de la torre en otro DataFrame
df_tower = pd.read_csv("synthetic_tower_hourly_3days.csv")

In [4]:
# Mostrar las primeras 5 filas del archivo del datacenter
df_dc.head()

,timestamp,it_load_kW,hvac_kW,ups_kW,total_consumption_kW,pue,temperature_C
0,2025-01-01 00:00:00,274.908024,100.552212,28.545215,404.005450,1.469602,22.277798
1,2025-01-01 01:00:00,390.142861,181.546143,21.106608,592.795613,1.519432,25.225440
2,2025-01-01 02:00:00,346.398788,170.685734,38.286930,555.371453,1.603272,24.547430
3,2025-01-01 03:00:00,319.731697,172.900717,35.080371,527.712784,1.650486,25.944564
4,2025-01-01 04:00:00,231.203728,177.127035,21.544363,429.875125,1.859291,24.603290

In [5]:
# Mostrar las primeras 5 filas del archivo de la torre
df_tower.head()

,timestamp,radio_load_kW,battery_soc_%,generator_kW,total_consumption_kW,ambient_temp_C
0,2025-01-01 00:00:00,7.865413,95.860168,0.555987,8.421400,20.370488
1,2025-01-01 01:00:00,10.908333,67.621845,2.463126,13.371458,16.835177
2,2025-01-01 02:00:00,5.305002,100.000000,0.056768,5.361771,11.409387
3,2025-01-01 03:00:00,5.373482,60.479122,2.343303,7.716785,31.618059
4,2025-01-01 04:00:00,13.226006,78.482149,0.281516,13.507522,30.322525

In [6]:
# Mostrar las columnas disponibles en ambos archivos
df_dc.columns, df_tower.columns

(Index(['timestamp', 'it_load_kW', 'hvac_kW', 'ups_kW', 'total_consumption_kW',
        'pue', 'temperature_C'],
       dtype='object'),
 Index(['timestamp', 'radio_load_kW', 'battery_soc_%', 'generator_kW',
        'total_consumption_kW', 'ambient_temp_C'],
       dtype='object'))